# Generated by Django 5.1.6 on 2025-02-11 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=50, null=True, verbose_name='Место действия')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала выполнения')),
                ('action', models.CharField(max_length=150, verbose_name='Описание действия')),
                ('is_pleasurable', models.BooleanField(default=False, verbose_name='Приятная привычка')),
                ('regularity', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Периодичность в днях')),
                ('reward', models.CharField(blank=True, max_length=150, null=True, verbose_name='Вознаграждение')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Длительность')),
                ('is_public', models.BooleanField(default='False', verbose_name='Публичная')),
                ('associated_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
