# Generated by Django 5.1.6 on 2025-02-18 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='regularity',
            field=models.PositiveIntegerField(default=1, verbose_name='Периодичность в днях'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_time',
            field=models.TimeField(default='12:00:00', verbose_name='Время начала выполнения'),
        ),
    ]
